services:
  server:
    container_name: debug_test_api
    environment:
      - DB_NAME=playersdb
      - DB_CONNECTION=mongodb://players:playerspass@db:27017
    depends_on:
      - db
    tty: true
  db:
    container_name: debug_test_db
    volumes:
    - "test_db:var/lib/mongodb/data"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpass
      - MONGO_INITDB_DATABASE=playersdb
volumes:
  test_db:
networks:
  default:
    name: debug_test