version: '3'
services:
  server:
    container_name: quizz_dev_api
    image: node:12.18.4
    working_dir: /code
    ports:
      - 8080:8080
    environment:
      - DB_NAME=playersdb
      - DB_CONNECTION=mongodb://admin:adminpass@db:27017
    depends_on:
      - db
    volumes:
    - type: bind
      source: ./api
      target: /code
    command: bash -c "npm install && npm start"
  db:
    container_name: quizz_dev_db
    image: mongo:latest
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=adminpass
    - MONGO_INITDB_DATABASE=playersdb
volumes:
  dbdata: