services:
  api:
    container_name: debug_test_api
    environment:
      - DB_NAME=playersdb
      - DB_CONNECTION=mongodb://admin:adminpass@db:27017
    depends_on:
      - db
    tty: true
  db:
    container_name: debug_test_db
    volumes:
    - "dbdata:/var/lib/mongodb/data"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpass
      - MONGO_INITDB_DATABASE=playersdb
volumes:
  dbdata:
networks:
  default:
    name: debug_test